### ISSUE TITLE
Create solution to sync github pages with CS servers

### ISSUE THREAD

**Issue by MartinMarwad** [UMLCloudComputing/UMLCloudComputing.github.io#6]
Related: https://github.com/UMLCloudComputing/react-mui-resume/issues/1

**Comment by MartinMarwad** [comment]
Perhaps for now we can include some sort of versioning so that the CS server copy can detect if it is out of date.

**Comment by Gurpranked** [comment]
Current implementation utilizes a simple cronjob to periodically sync the main branch of the repo to the cs.uml.edu domain's content. 
Future ideas for more optimization such as a selective syncing instead of a period system are on the table. Issue is solve at it's definition.

**Comment by Gurpranked** [comment]
More advanced CI/CD could be done through github itself for the gh pages and then inherited to cs.uml.edu domain page.
